;;; ellit-org.el --- Emacs Lisp Literate programming tool  -*- lexical-binding:t -*-

;; Copyright (C) 2020 by Zajcev Evgeny.

;; Author: Zajcev Evgeny <zevlg@yandex.ru>
;; Created: Wed Jan 22 10:35:15 2020
;; Keywords: convenience
;; Package-Requires: ((emacs "25.1"))
;; URL: https://github.com/zevlg/ellit-org.el
;; Version: 0.1
(defconst ellit-org-version "0.1")

;; ellit-org is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; ellit-org is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with ellit-org.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; #+OPTIONS: timestamp:nil \n:t
;; #+TITLE: [[ellit-org-logo64.png]] ellit-org (v{{{eval(ellit-org-version,t)}}})
;; #+STARTUP: showall
;;
;; #+BEGIN_QUOTE
;; This file is automatically generated from {{{ellit-filename(verbatim)}}} by
;; [[https://github.com/zevlg/ellit-org.el][GitHub#ellit-org.el]] tool.
;; Do not edit manually.
;; #+END_QUOTE
;;
;; Ultimate tool to document your Emacs Lisp project without much effort.
;;
;; Generate documentation for your Emacs Lisp package by combining
;; =.org= files and useful bits from comments in =.el= files.
;;
;; Idea is similar to https://github.com/tumashu/el2org
;;
;; However ellit-org implements more features, such as:
;; - Easy to use comments extractor from =.el=, see [[#commenting-el-files][Commenting files]]
;; - Combining multiple files, =.org= or =.el=
;; - [[#templates][Templating]]
;;
;; * Why?
;;
;; Separate files for code and documentation is hard to get in sync.
;; Once changing something in source code files, you might change
;; comments as well and forget about documentation.  In other words
;; having documentation in source code is easier to maintain for the
;; developers.
;;
;; Also many things, useful for documentation, might be automatically
;; extracted from source code.  Such as:
;; - Keybindings
;; - Customizable options
;; - Docstrings for commands
;; - etc
;;
;; * Using ellit-org in your project
;;
;; Sample Makefile to generate user manual for the project:
;;
;; #+BEGIN_SRC Makefile
;; EMACS=emacs -Q
;;
;; manual.org: srcfile.el <list-of-other-files-used-to-generate-manual>
;;      $(EMACS) -batch -f package-initialize -l ellit-org \
;;                  --eval '(ellit-org-export "srcfile.el" "manual.org")'
;; #+END_SRC
;;
;; ** Projects that uses ellit-org
;;    - ellit-org itself, see [[https://github.com/zevlg/ellit-org.el/blob/master/Makefile][Makefile]]
;;    - [[https://github.com/zevlg/telega.el][telega.el]], see its [[https://github.com/zevlg/telega.el/blob/master/doc/Makefile][Makefile]] to build documentation
;;    - [[https://github.com/zevlg/grammarbot.el][grammarbot.el]], see its [[https://github.com/zevlg/grammarbot.el/blob/master/Makefile][Makefile]]
;;
;; * Commenting .el files
;;
;; 1. Use double-semicolon comments, otherwise processing won't start
;; 2. Processing starts when Org mode's property, heading or list is seen
;; 3. Processing starts only if matched comment line begins commentary
;;    block, i.e. previous line is a non-commentary line
;; 4. Processing stops on any non-commentary line
;; 5. When processing stops, newline is emmited to output
;;
;; Here is the example:
;; #+BEGIN_SRC emacs-lisp
;;   ;; * Heading1                        <--- processing starts here
;;   ;; This line is included into output
;;   ;;
;;   ;; This line also included into output
;;                                        <--- processing stops here
;;   ;; This line is NOT included into output
;;   ;; * This line also NOT included
;;   ;;   Since it does not begin the commentary block, see 3.
;;
;;   ;; - However this line, is included  <--- processing starts here
;;   ;;
;;   ;;    Since new processing is started, and it will stop only on
;;   ;;    non-commentary line below
;;                                        <--- processing stops here
;;   ;; This line is *not* included
;; #+END_SRC


;;; Code:
(require 'subr-x)                       ;`replace-region-contents'
(require 'org)
(require 'ox-org)
(require 'svg)                          ;for `ellit-org--logo-image'

(defconst ellit-org-comment-start-regexp
  (rx (0+ (regexp "\s")) ";;"
      (or (regexp "\s") eol)))

(defvar ellit-org-start-regexp
  (rx (or buffer-start
          (and line-start (0+ (not ";")) "\n"))

      line-start (0+ (regexp "\s")) ";;" (1+ space)
      (or "#+"
          (and (or (1+ "*") "+" "-"
                   (and (1+ digit) (or "." ")")))
               space)))
  "Regexp matching start of the text to extract.")

;; * Templates
;;
;; ellit-org relies on Org mode's macro system by adding some useful
;; macroses.  See https://orgmode.org/manual/Macro-replacement.html
;;
;; Macro replacement is done *after* processing comments, so make
;; sure your macroses are in processed part of the comments.
;;
;; Templates syntax:
;; #+BEGIN_EXAMPLE
;; {{{macro_name(arguments)}}}
;; #+END_EXAMPLE
;;
;; ~ARGUMENTS~ are optional string supplied to function which does
;; processing for ~MACRO_NAME~.
;;
;; Supported templates:

(defvar ellit-org-macro-templates
  '(
    ;; - eval(~SEXP~ [, ~AS-STRING~ ]) ::
    ;;   {{{fundoc(ellit-org-template-eval, 2)}}}
    ("eval" . "(eval (ellit-org-template-eval $1 $2))")

    ;; - as-is(~STRING~) ::
    ;;   {{{fundoc1(ellit-org-template-as-is)}}}
    ;;
    ;;   ~as-is(STRING)~ filter is equivalent to ~eval("STRING")~
    ("as-is" . "(eval (ellit-org-template-as-is $1))")

    ;; - ellit-filename([ ~VERBATIM~ ]) ::
    ;;   {{{fundoc(ellit-org-template-ellit-filename, 2)}}}
    ("ellit-filename" . "(eval (ellit-org-template-ellit-filename $1))")

    ;; - kbd(~KEY~) ::
    ;;   {{{fundoc(ellit-org-template-kbd, 2)}}}
    ("kbd" . "(eval (ellit-org-template-kbd $1))")

    ;; - where-is(~COMMAND~, ~KEYMAP~) ::
    ;;   {{{fundoc(ellit-org-template-where-is, 2)}}}
    ("where-is" . "(eval (ellit-org-template-where-is $1 $2))")

    ;; - vardoc1(~VARIABLE~) ::
    ;;   {{{fundoc(ellit-org-template-vardoc1, 2)}}}
    ("vardoc1" . "(eval (ellit-org-template-vardoc1 $1))")

    ;; - vardoc(~VARIABLE~ [, ~INDENT-LEVEL~ ]) ::
    ;;   {{{fundoc(ellit-org-template-vardoc, 2)}}}
    ("vardoc" . "(eval (ellit-org-template-vardoc $1 $2))")

    ;; - fundoc1(~FUNCTION~) ::
    ;;   {{{fundoc(ellit-org-template-fundoc1, 2)}}}
    ("fundoc1" . "(eval (ellit-org-template-fundoc1 $1))")

    ;; - fundoc(~FUNCTION~ [, ~INDENT-LEVEL~ ]) ::
    ;;   {{{fundoc(ellit-org-template-fundoc, 2)}}}
    ("fundoc" . "(eval (ellit-org-template-fundoc $1 $2))")
    )
  "Alist of org macro templates.
Each element in form:
  (NAME . TEMPLATE)

See `org-macro-templates'.")

(defvar ellit-org--filename nil
  "Currently processing filename.
Used in `ellit-filename' template.")

(defun ellit-org--process-el ()
  "Extract org bits from emacs lisp comments of current buffer."
  (save-excursion
    (goto-char (point-min))
    (let (cpont)
      (while (progn (setq cpont (point))
                    (re-search-forward ellit-org-start-regexp nil 'no-error))
        (beginning-of-line)
        (delete-region cpont (point))

        ;; Scan line by line, stopping at non-commentary string
        (while (looking-at ellit-org-comment-start-regexp)
          (let ((del-point (match-end 0))
                (eol-point (point-at-eol)))
            ;; DO NOT strip "\n"
            (when (> del-point eol-point)
              (setq del-point eol-point))
            (delete-region (point) del-point))

          (forward-line 1)
          (beginning-of-line))
        (delete-region (point-at-bol) (point-at-eol))

        ;; NOTE: Separent processing hunks with newline
        (insert "\n"))

      (delete-region cpont (point-max))

      ;; Unneeded newline from processing last hunk
      (when (eq (char-before) ?\n)
        (delete-char -1))
      )))

(defun ellit-org--parse-include-args (element)
  "Parse arguments of #+ELLIT-INCLUDE keyword ELEMENT.
Return list where first element is filename and rest are properties."
  (let* ((value (org-element-property :value element))
         (file (and (string-match (rx line-start (1+ (not space)))
                                  value)
                    (prog1 (match-string 0 value)
                      (setq value (replace-match "" nil nil value)))))
         (no-load (when (string-match (regexp-quote ":no-load")
                                      value)
                    (setq value (replace-match "" nil nil value))
                    t)))
    (list file :no-load no-load)))

(defun ellit-org--process-org (&optional props)
  "Process all ELLIT-INCLUDE keywords in current org buffer.
PROPS are properties, such as: `:heading'."
  ;; init org regexps
  (let ((org-inhibit-startup t)) (org-mode))

  ;; TODO: support for `:heading' property to include only given
  ;; heading.  Do it by removing everything except for `:heading'
  ;; contents

  ;; Expand all #+ELLIT-INCLUDE keywords
  (let ((ellit-include-re "^[ \t]*#\\+ELLIT-INCLUDE:")
        (heading (plist-get props :heading)))
    (goto-char (point-min))
    (while (re-search-forward ellit-include-re nil t)
      (unless (org-in-commented-heading-p)
        (let ((element (save-match-data (org-element-at-point))))
          (when (eq (org-element-type element) 'keyword)
            (beginning-of-line)
            (let ((include-args (ellit-org--parse-include-args element)))
              ;; delete #+ELLIT-INCLUDE: keyword
              (delete-region (point) (line-beginning-position 2))
              (apply #'ellit-org--include include-args))))))))

(defun ellit-org--include (ellit-file &rest props)
  "Include ELLIT-FILE.
PROPS is plist of properties, such as:
  `:heading' - To include only given heading
  `:no-load' - Do not load .el ELLIT-FILE, loading is required to make
               macroses like {{{fundoc(xxx)}}} work."
  (let* ((ellit-dir (when ellit-org--filename
                      (file-name-directory ellit-org--filename)))
         (ellit-org--filename (expand-file-name ellit-file ellit-dir)))
    (insert (with-temp-buffer
              (insert-file-contents ellit-org--filename)

              (when (equal "el" (file-name-extension ellit-org--filename))
                (unless (plist-get props :no-load)
                  (condition-case err
                      (let ((load-prefer-newer t))
                        (load-file ellit-org--filename))
                    (t
                     (error "Error loading \"%s\": %S"
                            ellit-org--filename err))))
                (ellit-org--process-el))

              (ellit-org--process-org props)
              (buffer-string)))))

(defun ellit-org--insert-macros ()
  "Insert macroses from `ellit-org-macro-templates'."
  (dolist (macro ellit-org-macro-templates)
    (insert "#+MACRO: " (car macro) "   " (cdr macro) "\n")))


;;; Ellit-Org export backend, retains `html' export snippets
(defun ellit-org-export-snippet (export-snippet _contents _info)
  "Transcode a EXPORT-SNIPPET object from Org to ellit-org.
Retains `html' export snippets.
CONTENTS is nil.  INFO is a plist holding contextual information."
  (when (eq (org-export-snippet-backend export-snippet) 'html)
    (concat "@@html:" (org-element-property :value export-snippet) "@@")))

(org-export-define-derived-backend 'ellit-org 'org
  :translate-alist '((export-snippet . ellit-org-export-snippet)))

;;;
;;;###autoload
(defun ellit-org-export (ellit-file output-org-file &rest props)
  "Export ELLIT-FILE to OUTPUT-ORG-FILE.
ELLIT-FILE could be one of \".org\" or \".el\".
PROPS is following property list:
  `:no-load' - Do not load corresponding .el file.
  `:heading' - Export only this heading section from ELLIT-FILE.
  `:no-ellit-macros' - Do not install ellit macro templates."
  (with-temp-buffer
    (apply #'ellit-org--include ellit-file props)
    ;; NOTE: `ellit-org--filename' is set for {{{ellit-filename}}} macro
    (let ((ellit-org--filename (expand-file-name ellit-file))
          (org-export-global-macros
           (nconc (unless (plist-get props :no-ellit-macros)
                    (copy-sequence ellit-org-macro-templates))
                  org-export-global-macros)))
      (org-export-to-file 'ellit-org output-org-file))))

(defun ellit-org--logo-image (&optional size debug-p)
  "Generate logo for the `ellit-org'."
  (unless size (setq size 256))
  (let* ((logo-svg (svg-create size size))
         (border-size (/ size 32))
         (bracket-w (/ (- size (* border-size 1)) 8)))
    (svg-gradient logo-svg "cgrad1" 'linear
                  (list '(0 . "#8280c2") (cons size "#9146bc")))
    (svg-circle logo-svg (/ size 2) (/ size 2) (- (/ size 2) border-size)
                :stroke-width border-size
                :stroke-color "#592a80"
                :gradient "cgrad1")
    ;; Draw brackets
    (dotimes (n 6)
      (let ((x-off (+ (* border-size 2) (* n bracket-w))))
        ;; NOTE: swap `b-x' and `m-x' after third bracket
        (when (> n 2)
          (setq x-off (+ x-off (* 1.75 border-size))))

        (svg-text logo-svg (if (> n 2) "}" "{")
                  :font-size (/ size 1.75)
;                  :font-weight "bold"
                  :fill "white"
                  :font-family "OpenSans"
                  :x x-off
                  :y (+ (/ size 6.25) (/ size 2)))
        ))

    (when debug-p
      (svg-line logo-svg (/ size 2) 0 (/ size 2) size
                :stroke-width 1
                :stroke-color "black")
      (svg-line logo-svg 0 (/ size 2) size (/ size 2)
                :stroke-width 1
                :stroke-color "black"))

    (svg-image logo-svg :scale 1.0
               :width size :height size
               :ascent 'center)))

(defun ellit-org--save-logo (file &optional size)
  "Write ellit svg logo into FILE."
  (let ((logo-image (ellit-org--logo-image size)))
    (write-region "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" nil
                  file nil 'quiet)
    (write-region (plist-get (cdr logo-image) :data) nil
                  file 'append 'quiet)))


;;; Templates
(defun ellit-org-template-eval (sexp &optional as-string)
  "Insert results of the SEXP evaluation.
If AS-STRING is non-nil then use \"%s\" instead of \"%S\" for
formatting SEXP."
  (let ((as-string-p (not (string-empty-p as-string))))
    (format (if as-string-p "%s" "%S") (eval (read sexp)))))

(defun ellit-org-template-as-is (string)
  "Insert STRING as is."
  string)

(defun ellit-org-template-ellit-filename (&optional verbatim)
  "Insert currently processing filename.
If VERBATIM is specified, then outline filename with verbatim markup."
  (let ((verbatim-p (not (string-empty-p verbatim))))
    (concat (when verbatim-p "=")
            (file-name-nondirectory ellit-org--filename)
            (when verbatim-p "="))))

(defun ellit-org-template-kbd (key)
  "Insert HTML <kbd> tag with KEY contents."
  (concat "@@html:<kbd>@@" key "@@html:</kbd>@@"))

(defun ellit-org-template-where-is (command &optional keymap)
  "Insert list of keys that calls COMMAND.
KEYMAP is keymap where to lookup for COMMAND.  By default
`global-map' is considered."
  ;; {{{kbd(C-c 1)}}}, {{{kbd(C-c 2)}}} (~command~)
  (let ((cmd-sym (intern command))
        (keymap-sym (intern keymap)))
    (concat (mapconcat (lambda (key)
                         (ellit-org-template-kbd (key-description key)))
                       (where-is-internal cmd-sym (symbol-value keymap-sym))
                       ", ")
            " (~" command "~)")))

(defun ellit--indented-docstring (docstring indent-level)
  (if (and indent-level (not (string-empty-p indent-level)))
      (mapconcat #'identity (split-string docstring "\n")
                 (concat "\n" (make-string
                               (string-to-number indent-level) ?\s)))
    docstring))

(defun ellit-org--vardoc (varname &optional first-line-p)
  "Return docstring for the variable named by VARNAME.
If FIRST-LINE-P is non-nil, then return only first line of the docstring."
  (let* ((varsym (intern varname))
         (vardoc (documentation-property varsym 'variable-documentation t)))
    ;; Strip leading "*", seen in custom var docstring
    (when vardoc
      (replace-regexp-in-string
       (rx "`" (group (regexp "[^']+")) "'")
       "~\\1~"
       (string-trim-left
        (if first-line-p
            (car (split-string vardoc "\n"))
          vardoc)
        (concat "^" (regexp-quote "*")))))))

(defun ellit-org-template-vardoc1 (variable)
  "Insert first line from docstring for the VARIABLE."
  (ellit-org--vardoc variable 'first-line))

(defun ellit-org-template-vardoc (variable &optional indent-level)
  "Insert full docstring for the VARIABLE."
  (ellit--indented-docstring (ellit-org--vardoc variable) indent-level))

(defun ellit-org--funargs (funsym)
  "Return list of FUNSYM function arguments as list of strings."
  (cl-remove-if
   (lambda (s)
     (string-prefix-p "&" s))
   (mapcar 'upcase
           (mapcar 'symbol-name (help-function-arglist funsym)))))

(defun ellit-org--fundoc (funname &optional first-line-p)
  "Return docstring for the function named by FUNNAME.
If FIRST-LINE-P is non-nil, then return only first line of the docstring."
  (let* ((funsym (intern funname))
         (fundoc (documentation funsym t)))
    ;; NOTE: emphasize arguments refs in fundoc with ~...~ syntax
    ;; TODO: emphasize `xxx' syntax
    (when fundoc
      (let (case-fold-search)
        (replace-regexp-in-string
         (rx "`" (group (regexp "[^']+")) "'")
         "~\\1~"
         (replace-regexp-in-string
          (concat "\\<" (regexp-opt (ellit-org--funargs funsym)) "\\>")
          "~\\&~"
          (if first-line-p
              (car (split-string fundoc "\n"))
            fundoc))
         )))))

(defun ellit-org-template-fundoc1 (function)
  "Insert first line from docstring for the FUNCTION."
  (ellit-org--fundoc function 'first-line))

(defun ellit-org-template-fundoc (function &optional indent-level)
  "Insert full docstring for the FUNCTION."
  (ellit--indented-docstring (ellit-org--fundoc function) indent-level))

(provide 'ellit-org)

;;; ellit-org.el ends here
